apiVersion: v1
kind: Secret
metadata:
  name: postgres-init-script
type: Opaque
data:
  postgres-init-script.sql: Q1JFQVRFIFVTRVIga2V5Y2xvYWtkYnVzZXI7CkNSRUFURSBEQVRBQkFTRSBrZXljbG9hazsKR1JBTlQgQUxMIFBSSVZJTEVHRVMgT04gREFUQUJBU0Uga2V5Y2xvYWsgVE8ga2V5Y2xvYWtkYnVzZXI7CkFMVEVSIFVTRVIga2V5Y2xvYWtkYnVzZXIgd2l0aCBlbmNyeXB0ZWQgcGFzc3dvcmQgJ2tleWNsb2FrZGJwYXNzJzs=
